### ISSUE TITLE
API Auth

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-mirror#14]
- Set up a users table in Supabase to support API auth
- Implement authentication using your favorite framework, using flask_jwt seems like the most straightforward if you don't have another preference (https://blog.teclado.com/api-key-authentication-with-flask/)

**Comment by kalenluciano** [comment]
Flagging that [this PR](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/4) is ready for your review/assistance unblocking. Notes are in the PR itself. Let me know if you have any questions.

**Comment by e-linear** [comment]
Tagging myself in this as a reminder to review auth options.
