### ISSUE TITLE
Host API on Digital Ocean

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-mirror#15]
I'm getting this error when I try to deploy the API on Digital Ocean: 
```ImportError: cannot import name 'Mapping' from 'collections'```
- Verify flask app code on main branch will deploy locally in a clean virtual environment (install packages only from requirements.txt)
- When that runs without errors, debug any errors when trying to deploy on Digital Ocean: https://cloud.digitalocean.com/apps/f7334ee3-2cd0-483f-812d-7e3aed217ff8/settings/data-sources-app?i=feca0b

**Comment by josh-chamberlain** [comment]
I got this up, but I got a warning about how it's a development server.

```
INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
```

https://flask.palletsprojects.com/en/2.3.x/deploying/

I'll stop touching stuff for now.

**Comment by mbodeantor** [comment]
That's just referring to the fact that it's being hosted locally. This will be taken care of by DO
