### ISSUE TITLE
Quick Search Card

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-mirror#16]
Create a simple search card that has:

- PDAP logo at the top
- A short description of PDAP, what the user can expect to get from the search
- Text search field
- Text county field 
- Search button that submits the contents of the two fields to the [quick search API endpoint](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/3)
- Footer links to various portions of the PDAP site (see wireframe)

![Image](https://github.com/Police-Data-Accessibility-Project/data-sources-mirror/assets/96697114/f4d98d17-215c-47ff-bc75-06f648e20e93)

**Comment by josh-chamberlain** [comment]
These might be helpful: 

- Logo: https://docs.pdap.io/meta/about/staff/brand-assets
- Description: "Our mission is to help people locate, understand, and share public records about every U.S. police system. Try giving our database a search to see if we can help you find answers to your questions."

**Comment by kalenluciano** [comment]
Very barebones quick search card is complete. I still need to work on touching up the styling though.
