### ISSUE TITLE
Search Results Page

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-mirror#20]
Once a user has submitted their search query, they should see the results as multiple search result cards corresponding to each data source returned from the quick search endpoint. Includes:

- "Search Results" heading
- Text reflecting the search term submitted and the total number of results returned
- A button for the user to request additional data sources ([links here](https://airtable.com/app473MWXVJVaD7Es/shrbFfWk6fjzGnNsk))

![Image](https://github.com/Police-Data-Accessibility-Project/data-sources-mirror/assets/96697114/1b526d93-a226-45fc-ab87-cfd7d70ac36d)

**Comment by kalenluciano** [comment]
Search results page is functional with functional search results cards. I just need to work on styling now.
