### ISSUE TITLE
remove volunteers table

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-mirror#49]
I'm moving the volunteers table to a separate airtable database. We should stop mirroring it to DigitalOcean.

**Comment by josh-chamberlain** [comment]
@mbodeantor i'm not sure if the table being missing will break anything—I had to move it in a hurry

**Comment by mbodeantor** [comment]
I think it will break the mirror script, but should be a quick fix

**Comment by mbodeantor** [comment]
#50
