### ISSUE TITLE
Surveys record type

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-mirror#51]
added `Surveys` as a record_type, so we need to make sure we're expecting it when we mirror. Do we need an issue for data-sources-app as well? @mbodeantor 

docs updated: https://docs.pdap.io/activities/data-dictionaries/record-types-taxonomy

**Comment by mbodeantor** [comment]
@josh-chamberlain As this is not a new column I don't believe this would require any changes to the mirror or the data-sources-app
